"""Add About Author

Revision ID: 7ad47f4066f7
Revises: fc075879c1e7
Create Date: 2022-05-15 13:30:28.187365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ad47f4066f7'
down_revision = 'fc075879c1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('users', 'about_author')
    # ### end Alembic commands ###
